version: "3.3"

services:
  nginx:
    container_name: nginx
#    depends_on:
#      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    env_file: .env
    networks:
      - inception
#    volumes:
#      - wp-data:/var/www/html
    restart: always

networks:
  inception:
    driver: bridge
