version: "3.3"

##############  Services  #############
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:mariadb
    ports:
      - "3306"
    env_file: .env
    networks:
      - inception
    volumes:
      - sql-data:/var/lib/mysql
    restart: always


  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress:wordpress
    expose:
      - "9000"
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-data:/var/lib/mysql
    restart: always

##############  Networks  #############
networks:
  inception:
    driver: bridge

##############  Volumes  #############
volumes:
  wp-data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/ybellot/data/wordpress

  sql-data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/ybellot/data/mysql
