# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.3"

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    expose:
      - "9000"
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html # Path where our wordpress files are present
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    expose:
      - "3306"
    env_file: .env
    networks:
      - inception
    volumes:
      - sql-data:/var/lib/mysql
    restart: always

networks:
  inception:
    driver: bridge

# xavki: DOCKER-COMPOSE - 4. LES VOLUMES PERSISTANTS
# https://www.youtube.com/watch?v=HUXXKYA7j0s
volumes:
  wp-data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/ybellot/data/wordpress

  sql-data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/ybellot/data/mysql
